# Generated by Django 4.0.1 on 2022-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_pub_date_alter_newsstory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
